export const SHOW_FORM_PROJECT = 'SHOW_FORM_PROJECT';
export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const EDIT_FORM_PROJECT = 'EDIT_FORM_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ERROR_PROJECT = 'ERROR_PROJECT';

export const PROJECT_TASKS = 'PROJECT_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const ACTUAL_TASK = 'ACTUAL_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';
export const ERROR_TASK = 'ERROR_TASK';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const GET_USER = 'GET_USER';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOG_OUT = 'LOG_OUT';




